config/routes.rb
Rails.application.routes.draw do
  resources :restraunts, only: [:index, :show, :create, :new] do
    resources :reviews, only: [:create, :new]
  end
end

app/models/restraunt.rb
class Restraunt < ActiveRecord::Base
  has_many :reviews
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restraunt
  validates :rating, presence: true, numericality: {less_than_or_equal_to: 5}
  validates :restraunt_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/restraunts_controller.rb
class RestrauntsController < ApplicationController
  def index
    @restraunts = Restraunt.all
  end

  def show
    @restraunt = Restraunt.find(params[:id])
  end

  def create
    @restraunt = Restraunt.new(restraunt_params)

    if @restraunt.save
      flash[:notice] = "Created new restraunt!"
      redirect_to restraunt_path(@restraunt)
    else
      render :new
    end

  end

  def new
    @restraunt = Restraunt.new
  end

  private

  def restraunt_params
    params.require(:restraunt).
      permit(:name, :address, :city, :state, :zip_code, :description, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action { @restraunt = Restraunt.find(params[:restraunt_id]) }
  def new
    @review = Review.new
  end
  def create
    @review = Review.new(review_params)
    @restraunt = Restraunt.find(params[:restraunt_id])
    @review.restraunt = @restraunt

    if @review.save
      redirect_to @restraunt
      flash[:notice] = "Review created!"
    else
      render :new
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoodEats</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= notice %>
<%= yield %>

</body>
</html>

app/views/restraunts/index.html.haml
%ul
  - @restraunts.each do |restraunt|
    %li= link_to restraunt.name, restraunt_path(restraunt)

= link_to "Create new restraunt", new_restraunt_path

app/views/restraunts/new.html.haml
= form_for @restraunt do |f|

  -if @restraunt.errors.full_messages.any?
    %p You had some errors:
    %ul
      -@restraunt.errors.full_messages.each do |measage|
        %li= measage

  %p
    = f.label :name
    = f.text_field :name

  %p
    = f.label :address
    = f.text_field :address

  %p
    = f.label :city
    = f.text_field :city

  %p
    = f.label :state
    = f.text_field :state

  %p
    = f.label :zip_code
    = f.text_field :zip_code

  %p
    = f.label :description
    = f.text_field :description

  %p
    = f.label :category
    = f.text_field :category

  %p
    = f.submit

app/views/restraunts/show.html.haml
%h1= @restraunt.name

%h2= "#{@restraunt.address}, #{@restraunt.city}, #{@restraunt.state}, #{@restraunt.zip_code}"

%h3= @restraunt.category

%p= @restraunt.description

%ul
  - @restraunt.reviews.each do |review|
    %li
      = review.rating
      %p= review.body


= link_to "Write a review!", new_restraunt_review_path(@restraunt)

app/views/reviews/new.html.haml
= form_for [@restraunt, @review] do |f|

  -if @review.errors.full_messages.any?
    %p You had some errors:
    %ul
      -@review.errors.full_messages.each do |measage|
        %li= measage

  %p
    = f.label :rating
    = f.text_field :rating

  %p
    = f.label :body
    = f.text_field :body

  %p

    = f.submit